// Generated by packages/contracts/scripts/generate_types.py. Do not edit.
// Source: packages/contracts/schemas/contracts.schema.json

export type SearchMode = "keyword" | "vector" | "hybrid" | "weighted";

export type ReasoningEffort = "low" | "medium" | "high";

export type ExperimentStatus = "draft" | "queued" | "running" | "completed" | "failed";

export type EvaluationRunStatus = "queued" | "running" | "completed" | "failed";

export type MetricName = "retrieval_recall_at_k" | "mean_reciprocal_rank" | "ndcg_at_k" | "citation_precision" | "citation_recall" | "groundedness" | "answer_correctness" | "answer_rate" | "p50_latency_ms" | "total_tokens" | "estimated_cost_usd";

export interface ErrorDetail {
  code: string;
  message: string;
  details?: { [key: string]: unknown } | null;
}

export interface ErrorResponse {
  ok: false;
  error: ErrorDetail;
}

export interface IndexStatus {
  documents: number;
  parents: number;
  children: number;
  version: string;
}

export interface EmbeddingStatus {
  available: boolean;
  indexed: boolean;
  model: string;
}

export interface GenerationStatus {
  available: boolean;
  external: boolean;
  provider: string;
  model: string;
  reasoning: ReasoningEffort;
  context_char_budget: number;
  max_parent_ids: number;
  transmitted_data: string[];
}

export interface ModeStatus {
  available: boolean;
  external: boolean;
}

export interface SearchModes {
  keyword: ModeStatus;
  vector: ModeStatus;
  hybrid: ModeStatus;
  weighted: ModeStatus;
}

export interface CardFilterOption {
  id: string;
  label: string;
  document_id: string;
}

export interface IssuerFilterOption {
  id: string;
  label: string;
  cards: CardFilterOption[];
}

export interface StatusFilters {
  issuers: IssuerFilterOption[];
}

export interface ApiLimits {
  query_chars: number;
  top_k_max: number;
  candidate_k_max: number;
  answer_parent_ids_max: number;
}

export interface ModelOption {
  id: string;
  label: string;
  provider: string;
  available: boolean;
  external: boolean;
  unavailable_reason?: string | null;
}

export interface ModelCatalog {
  embeddings: ModelOption[];
  rerankers: ModelOption[];
  generation: ModelOption[];
}

export interface RerankConfiguration {
  enabled: boolean;
  top_n: number;
  /**
   * Share of the final score contributed by reranking. Use 0 when reranking is disabled.
   */
  weight: number;
}

export interface RetrievalConfiguration {
  mode: SearchMode;
  top_k: number;
  candidate_k: number;
  /**
   * Vector-score share in weighted search; keyword share is 1 - alpha.
   */
  alpha: number;
  issuer?: string | null;
  card_name?: string | null;
  reranking: RerankConfiguration;
}

export interface ModelConfiguration {
  /**
   * Must identify a compatible embedding/index pair advertised by GET /v1/status.
   */
  embedding: string;
  reranker: string | null;
  generation: string;
}

export interface GenerationConfiguration {
  reasoning: ReasoningEffort;
  prompt_id: string;
}

export interface RagConfiguration {
  retrieval: RetrievalConfiguration;
  models: ModelConfiguration;
  generation: GenerationConfiguration;
  index_version: string;
}

export interface StatusResponse {
  ok: true;
  service: "rag-api";
  index: IndexStatus;
  embedding: EmbeddingStatus;
  generation: GenerationStatus;
  modes: SearchModes;
  filters: StatusFilters;
  limits: ApiLimits;
  model_catalog: ModelCatalog;
  defaults: RagConfiguration;
}

export interface SearchRequest {
  query: string;
  mode?: SearchMode;
  top_k?: number;
  candidate_k?: number;
  issuer?: string | null;
  card_name?: string | null;
  alpha?: number;
  /**
   * Optional status-advertised model ID. Incompatible index/model pairs return 409.
   */
  embedding_model?: string;
  reranker_model?: string | null;
  rerank_top_n?: number;
  rerank_weight?: number;
}

export interface ChildMatch {
  chunk_id: string;
  text: string;
  page_start: number;
  page_end: number;
}

export interface ParentMatch {
  chunk_id: string;
  text: string;
  supporting_children: string[];
}

export interface SearchResult {
  rank: number;
  score: number | null;
  keyword_score: number | null;
  vector_score: number | null;
  rerank_score: number | null;
  document_id: string;
  issuer: string;
  card_name: string;
  page_start: number;
  page_end: number;
  section_path: string[];
  child: ChildMatch | null;
  parent: ParentMatch;
  citation: string;
  source_path: string | null;
  source_url: string | null;
}

export interface SearchResponse {
  ok: true;
  query: string;
  mode: SearchMode;
  top_k: number;
  candidate_k: number;
  alpha: number;
  latency_ms: number;
  index_latency_ms: number;
  embedding_used: boolean;
  embedding_latency_ms: number | null;
  embedding_tokens: number;
  embedding_model?: string | null;
  reranker_model?: string | null;
  results: SearchResult[];
}

export interface TokenUsage {
  input_tokens?: number;
  output_tokens?: number;
  total_tokens?: number;
  [key: string]: number | undefined;
}

export interface Citation {
  source_id: string;
  document_id: string;
  source_path: string | null;
  page_start: number;
  page_end: number;
  parent_id: string;
  supporting_children: string[];
  issuer: string;
  card_name: string;
  page: string;
  label: string;
  source_url: string | null;
  quote: string;
}

export interface ExternalTransmission {
  used: boolean;
  provider: string;
  data: string[];
}

export interface AnswerRetrieval {
  mode: SearchMode;
  top_k: number;
  candidate_k: number;
  selected_parent_ids: boolean;
  reexecuted: boolean;
  requested_parent_count: number;
  retrieved_parent_count: number;
  results: SearchResult[];
}

export interface AnswerRequest {
  query: string;
  mode?: SearchMode;
  top_k?: number;
  candidate_k?: number;
  issuer?: string | null;
  card_name?: string | null;
  alpha?: number;
  embedding_model?: string;
  reranker_model?: string | null;
  rerank_top_n?: number;
  rerank_weight?: number;
  parent_ids?: string[];
  /**
   * Must be an available model ID advertised by GET /v1/status.
   */
  generation_model?: string;
  reasoning?: ReasoningEffort;
  prompt_id?: string;
}

export interface AnswerResponse {
  ok: true;
  query: string;
  answer: string;
  citations: Citation[];
  insufficient_evidence: boolean;
  usage: TokenUsage;
  model: string;
  reasoning: ReasoningEffort;
  latency_ms: number;
  retrieval_latency_ms: number;
  generation_latency_ms: number;
  index_latency_ms: number;
  embedding_used: boolean;
  embedding_latency_ms: number | null;
  embedding_tokens: number;
  external_transmission: ExternalTransmission;
  retrieval: AnswerRetrieval;
}

export interface EvaluationMetrics {
  case_count: number;
  retrieval_recall_at_k?: number | null;
  mean_reciprocal_rank?: number | null;
  ndcg_at_k?: number | null;
  citation_precision?: number | null;
  citation_recall?: number | null;
  groundedness?: number | null;
  answer_correctness?: number | null;
  answer_rate?: number | null;
  p50_latency_ms?: number | null;
  total_tokens?: number | null;
  estimated_cost_usd?: number | null;
}

export interface CaseMetrics {
  retrieval_hit: number | null;
  reciprocal_rank: number | null;
  citation_precision: number | null;
  groundedness: number | null;
  answer_correctness: number | null;
}

export interface EvaluationCaseResult {
  case_id: string;
  query: string;
  expected_document_id: string;
  expected_page: number;
  expected_terms: string[];
  /**
   * Snapshot resolved from expected document/page/terms against the experiment index version.
   */
  resolved_expected_parent_ids: string[];
  retrieved_parent_ids: string[];
  answer: string | null;
  citations: Citation[];
  metrics: CaseMetrics;
  latency_ms: number;
  tokens: number;
  error: ErrorDetail | null;
}

export interface EvaluationRun {
  id: string;
  experiment_id: string;
  status: EvaluationRunStatus;
  created_at: string;
  started_at: string | null;
  completed_at: string | null;
  metrics: EvaluationMetrics | null;
  error: ErrorDetail | null;
}

export interface ExperimentCreateRequest {
  name: string;
  description?: string | null;
  dataset_id: string;
  configuration: RagConfiguration;
  tags?: string[];
}

export interface ExperimentSummary {
  id: string;
  name: string;
  description: string | null;
  dataset_id: string;
  configuration: RagConfiguration;
  tags: string[];
  status: ExperimentStatus;
  created_by: string;
  created_at: string;
  completed_at: string | null;
  metrics: EvaluationMetrics | null;
}

export interface ExperimentDetail {
  id: string;
  name: string;
  description: string | null;
  dataset_id: string;
  configuration: RagConfiguration;
  tags: string[];
  status: ExperimentStatus;
  created_by: string;
  created_at: string;
  completed_at: string | null;
  metrics: EvaluationMetrics | null;
  case_results: EvaluationCaseResult[];
  evaluation_runs: EvaluationRun[];
}

export interface ExperimentListResponse {
  items: ExperimentSummary[];
  next_cursor: string | null;
}

export interface ExperimentCompareRequest {
  baseline_experiment_id: string;
  candidate_experiment_ids: string[];
  include_case_deltas?: boolean;
  case_limit?: number;
}

export interface MetricComparisonValue {
  experiment_id: string;
  value: number | null;
  delta_from_baseline: number | null;
}

export interface MetricDelta {
  metric: MetricName;
  higher_is_better: boolean;
  baseline_value: number | null;
  candidates: MetricComparisonValue[];
}

export interface CaseComparisonValue {
  experiment_id: string;
  value: number | null;
  delta_from_baseline: number | null;
}

export interface CaseDelta {
  case_id: string;
  query: string;
  metric: MetricName;
  baseline_value: number | null;
  candidates: CaseComparisonValue[];
}

export interface ExperimentCompareResponse {
  baseline_experiment_id: string;
  experiments: ExperimentSummary[];
  metric_deltas: MetricDelta[];
  case_deltas: CaseDelta[];
}

export interface EvaluationRequest {
  experiment_id: string;
  case_ids?: string[];
}
