services:
  app:
    build: .
    ports:
      - "8501:8501"
      - "8888:8888"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./data:/app/data
      - ./sqlite_db:/app/sqlite_db
      - ./src:/app/src
      - ./prompts:/app/prompts
      - ./.streamlit:/app/.streamlit
      - ./app.py:/app/app.py
      - ./assets:/app/assets
    env_file:
      - .env
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0