from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
sys.path[:0] = [str(ROOT / "services/rag-api/src"), str(ROOT / "packages/rag-core/src")]


def ts_type(schema: dict[str, Any] | None) -> str:
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return f'components["schemas"]["{schema["$ref"].rsplit("/", 1)[-1]}"]'
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    if "allOf" in schema:
        return " & ".join(ts_type(item) for item in schema["allOf"])
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts_type({**schema, "type": item}) for item in kind)
    if kind == "array":
        return f"Array<{ts_type(schema.get('items'))}>"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        fields = [f"{json.dumps(name)}{'':s}{'' if name in required else '?'}: {ts_type(value)};" for name, value in sorted(properties.items())]
        additional = schema.get("additionalProperties")
        if additional:
            fields.append(f"[key: string]: {ts_type(additional if isinstance(additional, dict) else {})};")
        return "{ " + " ".join(fields) + " }"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def content_schema(value: dict[str, Any] | None) -> dict[str, Any] | None:
    return ((value or {}).get("content", {}).get("application/json") or {}).get("schema")


def render_types(openapi: dict[str, Any]) -> str:
    lines = ["// Generated by packages/contracts/generate.py. Do not edit.", "export interface components {", "  schemas: {"]
    for name, schema in sorted(openapi.get("components", {}).get("schemas", {}).items()):
        lines.append(f"    {json.dumps(name)}: {ts_type(schema)};")
    lines.extend(["  };", "}", "", "export interface operations {"])
    for path, path_item in sorted(openapi["paths"].items()):
        for method, operation in sorted(path_item.items()):
            if method not in {"get", "post", "put", "patch", "delete"}:
                continue
            request = ts_type(content_schema(operation.get("requestBody"))) if operation.get("requestBody") else "never"
            responses = "{ " + " ".join(f"{json.dumps(str(status))}: {ts_type(content_schema(response))};" for status, response in sorted(operation.get("responses", {}).items())) + " }"
            lines.append(f"  {json.dumps(method.upper() + ' ' + path)}: {{ requestBody: {request}; responses: {responses}; }};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def render() -> tuple[str, str]:
    from pickcardu_rag_api.main import create_app

    schema = create_app().openapi()
    yaml_text = yaml.safe_dump(schema, allow_unicode=True, sort_keys=True, width=120)
    return yaml_text, render_types(schema)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    yaml_text, types_text = render()
    outputs = {Path(__file__).with_name("openapi.yaml"): yaml_text, Path(__file__).with_name("generated") / "api.ts": types_text}
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, value in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != value]
        if stale:
            print("contract drift: " + ", ".join(stale))
            return 1
        return 0
    for path, value in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(value, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
