'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import type {ExperimentCompareResponse,ExperimentSummary,ExperimentDetail,SearchResponse} from '@/lib/contracts';
import {compareExperiments,listExperiments,evaluateExperiment,getExperiment} from '@/lib/rag-api';
import {registerSiteTools} from '@/lib/site-tools';
const percent=(v?:number|null)=>v==null?'—':`${(v*100).toFixed(1)}%`;
const labels:Record<string,string>={retrieval_recall_at_k:'Hit / Recall@K',mean_reciprocal_rank:'MRR',ndcg_at_k:'nDCG@K',p50_latency_ms:'중앙 검색 시간'};
export function CompareDashboard({user}:{user:{displayName:string;email:string}}){
 const [experiments,setExperiments]=useState<ExperimentSummary[]>([]),[baselineId,setBaselineId]=useState(''),[candidateId,setCandidateId]=useState('');
 const [comparison,setComparison]=useState<ExperimentCompareResponse|null>(null),[detail,setDetail]=useState<(ExperimentDetail & {search_snapshot:SearchResponse})|null>(null);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[toolsReady,setToolsReady]=useState(false);
 const refresh=useCallback(async()=>{const r=await listExperiments();setExperiments(r.items);return r;},[]);
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[refresh]);
 const compare=useCallback(async(baseline:string,candidate:string)=>{
   setError('');setBusy(true);
   try{const r=await compareExperiments({baseline_experiment_id:baseline,candidate_experiment_ids:[candidate],include_case_deltas:true});setBaselineId(baseline);setCandidateId(candidate);setComparison(r);return r;}
   catch(e){setError(e instanceof Error?e.message:'비교에 실패했습니다.');throw e;}finally{setBusy(false);}
 },[]);
 const resume=async(id:string)=>{setBusy(true);setError('');try{await evaluateExperiment({experiment_id:id},r=>setMessage(`평가 ${r.completed_cases}/${r.total_cases} · 이 페이지를 닫아도 진행 상황은 저장됩니다.`));setMessage('평가 완료');await refresh();}catch(e){setError(e instanceof Error?e.message:'평가를 이어가지 못했습니다.');}finally{setBusy(false);}};
 useEffect(()=>registerSiteTools([
  {name:'rag_list_experiments',title:'팀 실험 조회',description:'허가된 팀원들이 저장한 공용 실험 목록을 조회하고 화면을 갱신합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>refresh()},
  {name:'rag_compare_experiments',title:'팀 실험 비교',description:'같은 데이터·인덱스로 평가를 완료한 두 실험의 설정, 검색 지표, 질문별 차이를 화면에 표시합니다.',inputSchema:{type:'object',properties:{baseline_id:{type:'string'},candidate_id:{type:'string'}},required:['baseline_id','candidate_id'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input)=>{const p=input as {baseline_id:string;candidate_id:string};if(!p||typeof p.baseline_id!=='string'||typeof p.candidate_id!=='string')throw new Error('비교할 실험 ID가 필요합니다.');return compare(p.baseline_id,p.candidate_id);}},
 ],setToolsReady),[refresh,compare]);
 const selected=comparison?.experiments??experiments.filter(e=>e.id===baselineId||e.id===candidateId);
 return <main className="lab-shell compare-shell"><header className="lab-header"><div className="brand-lockup"><span>PickCardU</span><b>RAG LAB</b></div><nav aria-label="메뉴"><Link href="/">검색 실험</Link><Link className="active" href="/compare">팀 비교</Link></nav><div className="header-status"><span title={user.email}>{user.displayName}</span><a href="/signout-with-chatgpt?return_to=/" target="_top">로그아웃</a></div></header>
 <section className="compare-main"><div className="compare-intro"><div><span className="eyebrow">TEAM EXPERIMENTS</span><h1>함께 쌓고, 비교하는 실험.</h1><p>130개 고정 질문 · 문서·페이지·기대 문구 기반 근거 검색 평가</p></div><button className="refresh-button" disabled={busy} onClick={()=>void refresh().catch(e=>setError(e.message))}>목록 새로고침 ↻</button></div>
 {error?<p className="run-error" role="alert">{error}</p>:null}{message?<p className="save-message" role="status">{message}</p>:null}
 <section className="run-table-card"><div className="section-heading"><div><span className="eyebrow">SHARED RUNS</span><h2>팀 실험 기록</h2></div><button disabled={busy||!baselineId||!candidateId||baselineId===candidateId} onClick={()=>void compare(baselineId,candidateId).catch(()=>{})}>선택한 실험 비교 ↗</button></div><div className="run-table-wrap"><table className="run-table"><thead><tr><th>기준</th><th>비교</th><th>실험</th><th>작성자</th><th>방식 / α</th><th>평가</th><th>Recall@K</th><th>MRR</th></tr></thead><tbody>{experiments.length?experiments.map(e=><tr key={e.id}><td><input type="radio" name="baseline" aria-label={`${e.name} 기준 선택`} checked={baselineId===e.id} disabled={e.status!=='completed'||busy} onChange={()=>{setBaselineId(e.id);setComparison(null);}}/></td><td><input type="radio" name="candidate" aria-label={`${e.name} 비교 선택`} checked={candidateId===e.id} disabled={e.status!=='completed'||busy} onChange={()=>{setCandidateId(e.id);setComparison(null);}}/></td><td><button className="text-button" onClick={()=>void getExperiment(e.id).then(setDetail).catch(e=>setError(e.message))}>{e.name}</button><small>{new Date(e.created_at).toLocaleString('ko-KR')}</small></td><td>{e.created_by}</td><td>{e.configuration.retrieval.mode} / {e.configuration.retrieval.alpha.toFixed(2)}</td><td>{e.status==='completed'?<span className="run-status completed">완료</span>:<button disabled={busy} onClick={()=>void resume(e.id)}>평가 이어가기</button>}</td><td>{percent(e.metrics?.retrieval_recall_at_k)}</td><td>{percent(e.metrics?.mean_reciprocal_rank)}</td></tr>):<tr><td className="empty-table" colSpan={8}>아직 저장된 실험이 없습니다. <Link href="/">검색 실험 시작 →</Link></td></tr>}</tbody></table></div></section>
 <section className="comparison-grid">{selected.map(e=><article key={e.id} className={e.id===baselineId?'baseline-card':'candidate-card'}><span className="eyebrow">{e.id===baselineId?'BASELINE':'CANDIDATE'}</span><h2>{e.name}</h2><dl><div><dt>검색 방식</dt><dd>{e.configuration.retrieval.mode}</dd></div><div><dt>Vector 가중치</dt><dd>{Math.round(e.configuration.retrieval.alpha*100)}%</dd></div><div><dt>Top K / Candidate K</dt><dd>{e.configuration.retrieval.top_k} / {e.configuration.retrieval.candidate_k}</dd></div><div><dt>임베딩</dt><dd title={e.configuration.models.embedding}>{e.configuration.models.embedding}</dd></div><div><dt>인덱스 버전</dt><dd>{e.configuration.index_version.slice(0,12)}</dd></div><div><dt>평가 문항</dt><dd>{e.metrics?.case_count??0} / 130</dd></div></dl></article>)}</section>
 {comparison?<><section className="metric-card"><div className="section-heading"><h2>검색 지표 변화</h2></div><div className="metric-grid">{comparison.metric_deltas.map(m=>{const c=m.candidates[0];const latency=m.metric==='p50_latency_ms';const format=(v:number|null)=>v==null?'—':latency?`${v.toFixed(1)} ms`:percent(v);return <article key={m.metric}><span>{labels[m.metric]}</span><div><strong>{format(m.baseline_value)}</strong><b>→</b><strong>{format(c.value)}</strong></div><small>{c.delta_from_baseline==null?'—':`${c.delta_from_baseline>0?'+':''}${latency?c.delta_from_baseline.toFixed(1)+' ms':(c.delta_from_baseline*100).toFixed(1)+'%p'}`}</small></article>;})}</div><p className="metric-note">Recall@K는 기존 평가 정의인 정답 근거 적중률입니다. nDCG는 첫 정답 순위를 기준으로 합니다. 시간은 검색 계산만 측정하며, 모델 다운로드·질문 임베딩 시간은 제외합니다. 첨부 정답 중 1개는 기대 문구가 근거와 일치하지 않아 모든 실험에서 미적중으로 계산됩니다.</p></section><section className="metric-card"><div className="section-heading"><h2>질문별 비교 · MRR</h2></div><div className="run-table-wrap"><table className="run-table"><thead><tr><th>평가 질문</th><th>기준</th><th>비교</th><th>차이</th></tr></thead><tbody>{comparison.case_deltas.map(c=><tr key={c.case_id}><td className="query-cell">{c.query}</td><td>{percent(c.baseline_value)}</td><td>{percent(c.candidates[0]?.value)}</td><td>{percent(c.candidates[0]?.delta_from_baseline)}</td></tr>)}</tbody></table></div></section></>:null}
 {detail?<section className="metric-card"><div className="section-heading"><h2>{detail.name} · 저장된 검색 결과</h2><button onClick={()=>setDetail(null)}>닫기</button></div><div className="saved-detail"><p>{detail.search_snapshot.query}</p>{detail.search_snapshot.results.map(r=><details key={r.parent.chunk_id}><summary>{r.rank}. {r.card_name} · p. {r.page_start} · {r.score?.toFixed(3)}</summary><p className="full-text">{r.parent.text}</p></details>)}</div></section>:null}
 <p className="agent-note">{toolsReady?'Codex·Work 사이트 도구 연결됨':'허가된 팀원은 각자의 계정으로 같은 기록을 조회하고 비교할 수 있습니다.'}</p>
 </section></main>;
}
